version: '3.6'

services:
  verdaccio:
    image: verdaccio/verdaccio:5.8.0
    ports:
      - 4873
    volumes:
      - './configs/verdaccio/config.yaml:/verdaccio/conf/config.yaml'
  
  app:
    image: $DOCKER_IMAGE
    command: sleep infinity
    network_mode: service:verdaccio
    depends_on:
      - verdaccio