#!/bin/bash

set -euxo pipefail

DOCKER_IMAGE="$1"
NODE_VERSION=`cat .node-version`
PNPM_VERSION=`cat package.json | jq -r .packageManager | sed 's|^pnpm@||'`

docker build \
  --tag "$DOCKER_IMAGE" \
  --build-arg "PNPM_VERSION=$PNPM_VERSION" \
  --build-arg "NODE_VERSION=$NODE_VERSION" \
  .