#!/bin/bash

set -euxo pipefail

# create user
./scripts/ci/setup-verdaccio-user

# set registry
npm config set registry http://localhost:4873/

# publish dev release
./scripts/publish-snapshot-release


# test without storybook
SCRATCH_PATH="$HOME/without-storybook" \
  `pnpm bin`/jest tests/e2e/commands/create.test.ts

SCRATCH_PATH="$HOME/without-storybook" \
  `pnpm bin`/jest tests/e2e/commands/build.test.ts

SCRATCH_PATH="$HOME/without-storybook" \
  `pnpm bin`/jest tests/e2e/commands/dev.test.ts
