#!/bin/bash

set -euxo pipefail

# create user
./scripts/ci/setup-verdaccio-user

# set registry
npm config set registry http://localhost:4873/

# publish dev release
./scripts/publish-snapshot-release

# give this a try
npm init -y bgdk@dev ~/my-test-app
cd ~/my-test-app
yarn install
yarn build
