#!/usr/bin/env bash

set -euxo pipefail

# copy readmes into packages
cp ./README.md ./packages/bgdk/
cp ./README.md ./packages/storybook/

# copy in the example link
if [ -e "./packages/bgdk/examples" ]; then
  rm ./packages/bgdk/examples
fi

if [ -e "./packages/create-bgdk/examples" ]; then
  rm ./packages/create-bgdk/examples
fi

cp -r examples ./packages/bgdk/
cp -r examples ./packages/create-bgdk/

# build the packages
pnpm build