#!/usr/bin/env bash

set -euxo pipefail

# manually create the changeset
echo "---
'bgdk': patch
'@bgdk/storybook': patch
'bgdk-basic-example': patch
---

Snapshot Release
" > .changeset/snapshot.md

# bump versions
pnpm changeset version --snapshot dev

# build
pnpm ci:prepare

# publish - calling changeset directly as pnpm sets environment variables that overrides settings in .npmrc files
pnpm publish -r --tag dev --no-git-checks
# ./node_modules/.bin/changeset publish --tag dev
