#!/usr/bin/env bash

set -euxo pipefail

# manually create the changeset
echo "---
'bgdk': patch
'@bgdk/storybook': patch
---

Snapshot Release
" > .changeset/snapshot.md

# bump versions
yarn changeset version --snapshot dev

# build
yarn ci:prepare

# publish
./node_modules/.bin/changeset publish --tag dev
