#!/usr/bin/env bash

set -euxo pipefail

# manually create the changeset
echo "---
'bgdk': patch
'create-bgdk': patch
'@bgdk/storybook': patch
'bgdk-basic-example': patch
---

Snapshot Release
" > .changeset/snapshot.md

# bump versions
pnpm changeset version --snapshot dev

# build
pnpm ci:prepare

# changesets implements custom logic that revents registry from being sourced from .npmrc
export npm_config_registry=`npm config get registry`

pnpm changeset publish --tag dev
