# Based on https://github.com/verdaccio/github-actions/tree/master/publish
name: Setup Project
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@main

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: '6.24.2'

    - uses: actions/setup-node@main
      with:
        node-version: 14.x
        cache: 'pnpm'

    - run: pnpm i
      shell: bash
