# Based on https://github.com/verdaccio/github-actions/tree/master/publish
name: Setup Project
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@main
      with:
        node-version: 16.x
        cache: 'pnpm'

    - shell: bash
      run: corepack enable

    - shell: bash
      run: pnpm i
