# Based on https://github.com/verdaccio/github-actions/tree/master/publish
name: Setup Project
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v2
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - uses: actions/setup-node@main
      with:
        node-version: 14.x

    - run: yarn install --immutable
      shell: bash
