name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish & Deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/setup

      - name: Create release PR or publish to npm
        uses: changesets/action@master
        with:
          version: pnpm ci:version
          publish: pnpm ci:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
