name: Setup

on:
  workflow_call:

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@main

      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: actions/setup-node@main
        with:
          node-version: 14.x

      - uses: pnpm/action-setup@v2
        with:
          version: 6.16.1

      - run: pnpm install --frozen-lockfile
