name: Release

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Install
        run: yarn --immutable

      - name: Build
        run: yarn --immutable

      - name: Setup Verdaccio
        uses: ./.github/actions/setup-verdaccio

      - name: Switch registries
        uses: actions/setup-node@main
        with:
          node-version: 14.x
          registry-url: 'http://localhost:4873'

      - name: publish
        run: scripts/publish-snapshot-release
        env:
          npm_config_registry: 'http://localhost:4873'

      - run: npm cache clean --force

      - name: Create App
        run: npx bgdk@dev create test-app

      - name: Test Build Command
        run: node tests/e2e/build-comand.test.js

      - name: Test Dev Command
        run: node tests/e2e/dev-comand.test.js
