name: Test

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/setup-project

      - run: pnpm build

      - run: pnpm lint

      - run: scripts/test-e2e
