name: Test

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/setup-project

      - run: pnpm build

      - run: pnpm lint

      - uses: ./.github/actions/setup-verdaccio

      - name: Switch registries
        uses: actions/setup-node@main
        with:
          node-version: 14.x
          registry-url: 'http://localhost:4873'

      - name: publish
        run: scripts/publish-snapshot-release

      # without storybook

      - run: |
          `pnpm bin`/jest tests/e2e/commands/create.test.ts
        env:
          SCRATCH_PATH: ../test-workspace/test-1

      - run: |
          `pnpm bin`/jest tests/e2e/commands/build.test.ts
        env:
          SCRATCH_PATH: ../test-workspace/test-1

      - run: |
          `pnpm bin`/jest tests/e2e/commands/dev.test.ts
        env:
          SCRATCH_PATH: ../test-workspace/test-1

      # Storybook tests

      - run: |
          `pnpm bin`/jest tests/e2e/commands/create-storybook.test.ts
        env:
          SCRATCH_PATH: ../test-workspace/test-storybook

      - run: |
          `pnpm bin`/jest tests/e2e/commands/build.test.ts
        env:
          SCRATCH_PATH: ../test-workspace/test-storybook

      - run: |
          `pnpm bin`/jest tests/e2e/commands/dev.test.ts
        env:
          SCRATCH_PATH: ../test-workspace/test-storybook
